# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_training_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='categories',
            field=models.ManyToManyField(to='base.Category'),
        ),
    ]
