# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-03 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20161103_1934'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ALikes',
            new_name='ALike',
        ),
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='QLikes',
            new_name='QLike',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
