# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-05 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='alike',
            name='like',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qlike',
            name='like',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
