# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-06 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20161106_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alike',
            name='like',
            field=models.NullBooleanField(),
        ),
    ]
