# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-06 18:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0010_auto_20161106_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='tag',
            name='subcat',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertag',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Category'),
        ),
        migrations.AddField(
            model_name='usertag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
