# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-06 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20161106_2359'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='QTag',
        ),
    ]
