# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-06 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20161107_0004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTag',
            new_name='UTag',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Category'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
