# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-07 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20161107_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qlike',
            name='like',
            field=models.NullBooleanField(),
        ),
    ]
